Repository denodrivers/redis, pull requests merged in 2024-12, with the labels that each got.

#468 docs(README): `deno-redis` should be imported from JSR
  README.md
Labels: docs

#470 add self-signed root ca support for tls (fixes #469)
  connection.ts
Labels: enhancement

#471 feat: always use TLS if is specified
  connection.ts
Labels: enhancement

#472 feat: export experimental modules
  deno.json
  experimental/cluster/README.md
  experimental/cluster/mod.ts
  experimental/web_streams_connection/mod.ts
Labels: enhancement

#474 fix: failed to publish `0.36.0` to JSR
  deps/std/collections.ts
Labels: bug

#475 add connection event listener support similar to node-redis
  connection.ts
  mod.ts
  redis.ts
  tests/commands/connection.ts
Labels: enhancement

#476 feat: improve type-safety for events
  connection.ts
  events.ts
  mod.ts
  redis.ts
  tests/commands/connection.ts
Labels: enhancement

#484 fix: support long lines
  protocol/deno_streams/reply.ts
Labels: bug
